// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/pwh-pwh/Epidemic-prevention-System/dao/models"
)

func newAccessRegister(db *gorm.DB, opts ...gen.DOOption) accessRegister {
	_accessRegister := accessRegister{}

	_accessRegister.accessRegisterDo.UseDB(db, opts...)
	_accessRegister.accessRegisterDo.UseModel(&models.AccessRegister{})

	tableName := _accessRegister.accessRegisterDo.TableName()
	_accessRegister.ALL = field.NewAsterisk(tableName)
	_accessRegister.ID = field.NewInt64(tableName, "id")
	_accessRegister.Name = field.NewString(tableName, "name")
	_accessRegister.Phone = field.NewString(tableName, "phone")
	_accessRegister.Type = field.NewInt32(tableName, "type")
	_accessRegister.Card = field.NewString(tableName, "card")
	_accessRegister.Remark = field.NewString(tableName, "remark")
	_accessRegister.Dept = field.NewString(tableName, "dept")
	_accessRegister.CreateBy = field.NewString(tableName, "create_by")
	_accessRegister.CreateTime = field.NewTime(tableName, "create_time")
	_accessRegister.UpdateTime = field.NewTime(tableName, "update_time")
	_accessRegister.IsDelete = field.NewInt32(tableName, "is_delete")

	_accessRegister.fillFieldMap()

	return _accessRegister
}

type accessRegister struct {
	accessRegisterDo accessRegisterDo

	ALL        field.Asterisk
	ID         field.Int64  // 自增id
	Name       field.String // 姓名
	Phone      field.String // 手机号码
	Type       field.Int32  // 出入类型（1：出校 0：入校）
	Card       field.String // 身份证号
	Remark     field.String // 备注
	Dept       field.String // 部门
	CreateBy   field.String // 创建人
	CreateTime field.Time   // 创建时间
	UpdateTime field.Time   // 更新时间
	IsDelete   field.Int32  // 逻辑删除

	fieldMap map[string]field.Expr
}

func (a accessRegister) Table(newTableName string) *accessRegister {
	a.accessRegisterDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a accessRegister) As(alias string) *accessRegister {
	a.accessRegisterDo.DO = *(a.accessRegisterDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *accessRegister) updateTableName(table string) *accessRegister {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.Name = field.NewString(table, "name")
	a.Phone = field.NewString(table, "phone")
	a.Type = field.NewInt32(table, "type")
	a.Card = field.NewString(table, "card")
	a.Remark = field.NewString(table, "remark")
	a.Dept = field.NewString(table, "dept")
	a.CreateBy = field.NewString(table, "create_by")
	a.CreateTime = field.NewTime(table, "create_time")
	a.UpdateTime = field.NewTime(table, "update_time")
	a.IsDelete = field.NewInt32(table, "is_delete")

	a.fillFieldMap()

	return a
}

func (a *accessRegister) WithContext(ctx context.Context) *accessRegisterDo {
	return a.accessRegisterDo.WithContext(ctx)
}

func (a accessRegister) TableName() string { return a.accessRegisterDo.TableName() }

func (a accessRegister) Alias() string { return a.accessRegisterDo.Alias() }

func (a *accessRegister) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *accessRegister) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 11)
	a.fieldMap["id"] = a.ID
	a.fieldMap["name"] = a.Name
	a.fieldMap["phone"] = a.Phone
	a.fieldMap["type"] = a.Type
	a.fieldMap["card"] = a.Card
	a.fieldMap["remark"] = a.Remark
	a.fieldMap["dept"] = a.Dept
	a.fieldMap["create_by"] = a.CreateBy
	a.fieldMap["create_time"] = a.CreateTime
	a.fieldMap["update_time"] = a.UpdateTime
	a.fieldMap["is_delete"] = a.IsDelete
}

func (a accessRegister) clone(db *gorm.DB) accessRegister {
	a.accessRegisterDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a accessRegister) replaceDB(db *gorm.DB) accessRegister {
	a.accessRegisterDo.ReplaceDB(db)
	return a
}

type accessRegisterDo struct{ gen.DO }

func (a accessRegisterDo) Debug() *accessRegisterDo {
	return a.withDO(a.DO.Debug())
}

func (a accessRegisterDo) WithContext(ctx context.Context) *accessRegisterDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a accessRegisterDo) ReadDB() *accessRegisterDo {
	return a.Clauses(dbresolver.Read)
}

func (a accessRegisterDo) WriteDB() *accessRegisterDo {
	return a.Clauses(dbresolver.Write)
}

func (a accessRegisterDo) Session(config *gorm.Session) *accessRegisterDo {
	return a.withDO(a.DO.Session(config))
}

func (a accessRegisterDo) Clauses(conds ...clause.Expression) *accessRegisterDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a accessRegisterDo) Returning(value interface{}, columns ...string) *accessRegisterDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a accessRegisterDo) Not(conds ...gen.Condition) *accessRegisterDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a accessRegisterDo) Or(conds ...gen.Condition) *accessRegisterDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a accessRegisterDo) Select(conds ...field.Expr) *accessRegisterDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a accessRegisterDo) Where(conds ...gen.Condition) *accessRegisterDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a accessRegisterDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *accessRegisterDo {
	return a.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (a accessRegisterDo) Order(conds ...field.Expr) *accessRegisterDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a accessRegisterDo) Distinct(cols ...field.Expr) *accessRegisterDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a accessRegisterDo) Omit(cols ...field.Expr) *accessRegisterDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a accessRegisterDo) Join(table schema.Tabler, on ...field.Expr) *accessRegisterDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a accessRegisterDo) LeftJoin(table schema.Tabler, on ...field.Expr) *accessRegisterDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a accessRegisterDo) RightJoin(table schema.Tabler, on ...field.Expr) *accessRegisterDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a accessRegisterDo) Group(cols ...field.Expr) *accessRegisterDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a accessRegisterDo) Having(conds ...gen.Condition) *accessRegisterDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a accessRegisterDo) Limit(limit int) *accessRegisterDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a accessRegisterDo) Offset(offset int) *accessRegisterDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a accessRegisterDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *accessRegisterDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a accessRegisterDo) Unscoped() *accessRegisterDo {
	return a.withDO(a.DO.Unscoped())
}

func (a accessRegisterDo) Create(values ...*models.AccessRegister) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a accessRegisterDo) CreateInBatches(values []*models.AccessRegister, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a accessRegisterDo) Save(values ...*models.AccessRegister) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a accessRegisterDo) First() (*models.AccessRegister, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.AccessRegister), nil
	}
}

func (a accessRegisterDo) Take() (*models.AccessRegister, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.AccessRegister), nil
	}
}

func (a accessRegisterDo) Last() (*models.AccessRegister, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.AccessRegister), nil
	}
}

func (a accessRegisterDo) Find() ([]*models.AccessRegister, error) {
	result, err := a.DO.Find()
	return result.([]*models.AccessRegister), err
}

func (a accessRegisterDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.AccessRegister, err error) {
	buf := make([]*models.AccessRegister, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a accessRegisterDo) FindInBatches(result *[]*models.AccessRegister, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a accessRegisterDo) Attrs(attrs ...field.AssignExpr) *accessRegisterDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a accessRegisterDo) Assign(attrs ...field.AssignExpr) *accessRegisterDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a accessRegisterDo) Joins(fields ...field.RelationField) *accessRegisterDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a accessRegisterDo) Preload(fields ...field.RelationField) *accessRegisterDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a accessRegisterDo) FirstOrInit() (*models.AccessRegister, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.AccessRegister), nil
	}
}

func (a accessRegisterDo) FirstOrCreate() (*models.AccessRegister, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.AccessRegister), nil
	}
}

func (a accessRegisterDo) FindByPage(offset int, limit int) (result []*models.AccessRegister, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a accessRegisterDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a accessRegisterDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a accessRegisterDo) Delete(models ...*models.AccessRegister) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *accessRegisterDo) withDO(do gen.Dao) *accessRegisterDo {
	a.DO = *do.(*gen.DO)
	return a
}
