// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"github.com/pwh-pwh/Epidemic-prevention-System/models"
	"testing"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&models.GoodStock{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&models.GoodStock{}) fail: %s", err)
	}
}

func Test_goodStockQuery(t *testing.T) {
	goodStock := newGoodStock(db)
	goodStock = *goodStock.As(goodStock.TableName())
	_do := goodStock.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(goodStock.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <good_stock> fail:", err)
		return
	}

	_, ok := goodStock.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from goodStock success")
	}

	err = _do.Create(&models.GoodStock{})
	if err != nil {
		t.Error("create item in table <good_stock> fail:", err)
	}

	err = _do.Save(&models.GoodStock{})
	if err != nil {
		t.Error("create item in table <good_stock> fail:", err)
	}

	err = _do.CreateInBatches([]*models.GoodStock{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <good_stock> fail:", err)
	}

	_, err = _do.Select(goodStock.ALL).Take()
	if err != nil {
		t.Error("Take() on table <good_stock> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <good_stock> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <good_stock> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <good_stock> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*models.GoodStock{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <good_stock> fail:", err)
	}

	_, err = _do.Select(goodStock.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <good_stock> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <good_stock> fail:", err)
	}

	_, err = _do.Select(goodStock.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <good_stock> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <good_stock> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <good_stock> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <good_stock> fail:", err)
	}

	_, err = _do.ScanByPage(&models.GoodStock{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <good_stock> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <good_stock> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <good_stock> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), clause.PrimaryKey)

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <good_stock> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <good_stock> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <good_stock> fail:", err)
	}
}
