// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"github.com/pwh-pwh/Epidemic-prevention-System/models"
	"testing"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&models.SysLoginInfo{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&models.SysLoginInfo{}) fail: %s", err)
	}
}

func Test_sysLoginInfoQuery(t *testing.T) {
	sysLoginInfo := newSysLoginInfo(db)
	sysLoginInfo = *sysLoginInfo.As(sysLoginInfo.TableName())
	_do := sysLoginInfo.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(sysLoginInfo.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <sys_login_info> fail:", err)
		return
	}

	_, ok := sysLoginInfo.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from sysLoginInfo success")
	}

	err = _do.Create(&models.SysLoginInfo{})
	if err != nil {
		t.Error("create item in table <sys_login_info> fail:", err)
	}

	err = _do.Save(&models.SysLoginInfo{})
	if err != nil {
		t.Error("create item in table <sys_login_info> fail:", err)
	}

	err = _do.CreateInBatches([]*models.SysLoginInfo{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <sys_login_info> fail:", err)
	}

	_, err = _do.Select(sysLoginInfo.ALL).Take()
	if err != nil {
		t.Error("Take() on table <sys_login_info> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <sys_login_info> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <sys_login_info> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <sys_login_info> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*models.SysLoginInfo{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <sys_login_info> fail:", err)
	}

	_, err = _do.Select(sysLoginInfo.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <sys_login_info> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <sys_login_info> fail:", err)
	}

	_, err = _do.Select(sysLoginInfo.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <sys_login_info> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <sys_login_info> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <sys_login_info> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <sys_login_info> fail:", err)
	}

	_, err = _do.ScanByPage(&models.SysLoginInfo{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <sys_login_info> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <sys_login_info> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <sys_login_info> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), clause.PrimaryKey)

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <sys_login_info> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <sys_login_info> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <sys_login_info> fail:", err)
	}
}
