// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/pwh-pwh/Epidemic-prevention-System/models"
)

func newSysNotice(db *gorm.DB, opts ...gen.DOOption) sysNotice {
	_sysNotice := sysNotice{}

	_sysNotice.sysNoticeDo.UseDB(db, opts...)
	_sysNotice.sysNoticeDo.UseModel(&models.SysNotice{})

	tableName := _sysNotice.sysNoticeDo.TableName()
	_sysNotice.ALL = field.NewAsterisk(tableName)
	_sysNotice.ID = field.NewInt64(tableName, "id")
	_sysNotice.Title = field.NewString(tableName, "title")
	_sysNotice.Content = field.NewString(tableName, "content")
	_sysNotice.Status = field.NewInt32(tableName, "status")
	_sysNotice.CreateBy = field.NewString(tableName, "create_by")
	_sysNotice.UpdateBy = field.NewString(tableName, "update_by")
	_sysNotice.CreateTime = field.NewTime(tableName, "create_time")
	_sysNotice.UpdateTime = field.NewTime(tableName, "update_time")
	_sysNotice.IsDelete = field.NewInt32(tableName, "is_delete")
	_sysNotice.Remark = field.NewString(tableName, "remark")

	_sysNotice.fillFieldMap()

	return _sysNotice
}

type sysNotice struct {
	sysNoticeDo sysNoticeDo

	ALL        field.Asterisk
	ID         field.Int64
	Title      field.String
	Content    field.String
	Status     field.Int32
	CreateBy   field.String // 创建者
	UpdateBy   field.String // 更新者
	CreateTime field.Time
	UpdateTime field.Time
	IsDelete   field.Int32
	Remark     field.String

	fieldMap map[string]field.Expr
}

func (s sysNotice) Table(newTableName string) *sysNotice {
	s.sysNoticeDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysNotice) As(alias string) *sysNotice {
	s.sysNoticeDo.DO = *(s.sysNoticeDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysNotice) updateTableName(table string) *sysNotice {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Title = field.NewString(table, "title")
	s.Content = field.NewString(table, "content")
	s.Status = field.NewInt32(table, "status")
	s.CreateBy = field.NewString(table, "create_by")
	s.UpdateBy = field.NewString(table, "update_by")
	s.CreateTime = field.NewTime(table, "create_time")
	s.UpdateTime = field.NewTime(table, "update_time")
	s.IsDelete = field.NewInt32(table, "is_delete")
	s.Remark = field.NewString(table, "remark")

	s.fillFieldMap()

	return s
}

func (s *sysNotice) WithContext(ctx context.Context) *sysNoticeDo {
	return s.sysNoticeDo.WithContext(ctx)
}

func (s sysNotice) TableName() string { return s.sysNoticeDo.TableName() }

func (s sysNotice) Alias() string { return s.sysNoticeDo.Alias() }

func (s *sysNotice) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysNotice) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["title"] = s.Title
	s.fieldMap["content"] = s.Content
	s.fieldMap["status"] = s.Status
	s.fieldMap["create_by"] = s.CreateBy
	s.fieldMap["update_by"] = s.UpdateBy
	s.fieldMap["create_time"] = s.CreateTime
	s.fieldMap["update_time"] = s.UpdateTime
	s.fieldMap["is_delete"] = s.IsDelete
	s.fieldMap["remark"] = s.Remark
}

func (s sysNotice) clone(db *gorm.DB) sysNotice {
	s.sysNoticeDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysNotice) replaceDB(db *gorm.DB) sysNotice {
	s.sysNoticeDo.ReplaceDB(db)
	return s
}

type sysNoticeDo struct{ gen.DO }

func (s sysNoticeDo) Debug() *sysNoticeDo {
	return s.withDO(s.DO.Debug())
}

func (s sysNoticeDo) WithContext(ctx context.Context) *sysNoticeDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysNoticeDo) ReadDB() *sysNoticeDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysNoticeDo) WriteDB() *sysNoticeDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysNoticeDo) Session(config *gorm.Session) *sysNoticeDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysNoticeDo) Clauses(conds ...clause.Expression) *sysNoticeDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysNoticeDo) Returning(value interface{}, columns ...string) *sysNoticeDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysNoticeDo) Not(conds ...gen.Condition) *sysNoticeDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysNoticeDo) Or(conds ...gen.Condition) *sysNoticeDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysNoticeDo) Select(conds ...field.Expr) *sysNoticeDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysNoticeDo) Where(conds ...gen.Condition) *sysNoticeDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysNoticeDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *sysNoticeDo {
	return s.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (s sysNoticeDo) Order(conds ...field.Expr) *sysNoticeDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysNoticeDo) Distinct(cols ...field.Expr) *sysNoticeDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysNoticeDo) Omit(cols ...field.Expr) *sysNoticeDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysNoticeDo) Join(table schema.Tabler, on ...field.Expr) *sysNoticeDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysNoticeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *sysNoticeDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysNoticeDo) RightJoin(table schema.Tabler, on ...field.Expr) *sysNoticeDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysNoticeDo) Group(cols ...field.Expr) *sysNoticeDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysNoticeDo) Having(conds ...gen.Condition) *sysNoticeDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysNoticeDo) Limit(limit int) *sysNoticeDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysNoticeDo) Offset(offset int) *sysNoticeDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysNoticeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *sysNoticeDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysNoticeDo) Unscoped() *sysNoticeDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysNoticeDo) Create(values ...*models.SysNotice) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysNoticeDo) CreateInBatches(values []*models.SysNotice, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysNoticeDo) Save(values ...*models.SysNotice) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysNoticeDo) First() (*models.SysNotice, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysNotice), nil
	}
}

func (s sysNoticeDo) Take() (*models.SysNotice, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysNotice), nil
	}
}

func (s sysNoticeDo) Last() (*models.SysNotice, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysNotice), nil
	}
}

func (s sysNoticeDo) Find() ([]*models.SysNotice, error) {
	result, err := s.DO.Find()
	return result.([]*models.SysNotice), err
}

func (s sysNoticeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.SysNotice, err error) {
	buf := make([]*models.SysNotice, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysNoticeDo) FindInBatches(result *[]*models.SysNotice, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysNoticeDo) Attrs(attrs ...field.AssignExpr) *sysNoticeDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysNoticeDo) Assign(attrs ...field.AssignExpr) *sysNoticeDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysNoticeDo) Joins(fields ...field.RelationField) *sysNoticeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysNoticeDo) Preload(fields ...field.RelationField) *sysNoticeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysNoticeDo) FirstOrInit() (*models.SysNotice, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysNotice), nil
	}
}

func (s sysNoticeDo) FirstOrCreate() (*models.SysNotice, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.SysNotice), nil
	}
}

func (s sysNoticeDo) FindByPage(offset int, limit int) (result []*models.SysNotice, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysNoticeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysNoticeDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysNoticeDo) Delete(models ...*models.SysNotice) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysNoticeDo) withDO(do gen.Dao) *sysNoticeDo {
	s.DO = *do.(*gen.DO)
	return s
}
