// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAccessReturn = "access_return"

// AccessReturn mapped from table <access_return>
type AccessReturn struct {
	ID         int64     `gorm:"column:id;type:bigint(11);primaryKey;autoIncrement:true" json:"id"`          // 自增id
	Name       string    `gorm:"column:name;type:varchar(50);uniqueIndex:name_index,priority:1" json:"name"` // 姓名
	Phone      string    `gorm:"column:phone;type:varchar(60)" json:"phone"`                                 // 手机号码
	Card       string    `gorm:"column:card;type:varchar(80)" json:"card"`                                   // 身份证号码
	Remark     string    `gorm:"column:remark;type:varchar(255)" json:"remark"`                              // 备注
	Dept       string    `gorm:"column:dept;type:varchar(50)" json:"dept"`                                   // 部门
	CreateTime LocalTime `gorm:"column:create_time;type:datetime;autoCreateTime:true" json:"create_time"`    // 创建时间
}

// TableName AccessReturn's table name
func (*AccessReturn) TableName() string {
	return TableNameAccessReturn
}
