// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"gorm.io/plugin/soft_delete"
)

const TableNameLeaveApply = "leave_apply"

// LeaveApply mapped from table <leave_apply>
type LeaveApply struct {
	ID          int64                 `gorm:"column:id;type:bigint(11);primaryKey;autoIncrement:true" json:"id"`      // 主键id
	Username    string                `gorm:"column:username;type:varchar(50)" json:"username"`                       // 用户名
	DeptID      int64                 `gorm:"column:dept_id;type:bigint(11)" json:"dept_id"`                          // 部门id
	Reason      string                `gorm:"column:reason;type:varchar(255)" json:"reason"`                          // 请假原因
	LeaveType   int32                 `gorm:"column:leave_type;type:int(1)" json:"leave_type"`                        // 请假类型（1：事假 2：病假）
	Status      int32                 `gorm:"column:status;type:int(1)" json:"status"`                                // 状态（0：撤销 1：待审核 2：审核通过 3：审核不通过）
	StudentType int32                 `gorm:"column:student_type;type:int(1)" json:"student_type"`                    // 学生类型（1：本科生 2：研究生 3：博士生）
	Nickname    string                `gorm:"column:nickname;type:varchar(64)" json:"nickname"`                       // 学生姓名
	Time        string                `gorm:"column:time;type:varchar(64)" json:"time"`                               // 请假时间区间
	Day         string                `gorm:"column:day;type:varchar(50)" json:"day"`                                 // 请假天数
	Address     string                `gorm:"column:address;type:varchar(100)" json:"address"`                        // 目的地
	Traffic     string                `gorm:"column:traffic;type:varchar(50)" json:"traffic"`                         // 交通工具
	Clazz       int32                 `gorm:"column:clazz;type:int(1)" json:"clazz"`                                  // 是否有课程（1：没有 0：有）
	Dormitory   string                `gorm:"column:dormitory;type:varchar(50)" json:"dormitory"`                     // 宿舍
	PhoneNumber string                `gorm:"column:phone_number;type:varchar(50)" json:"phone_number"`               // 手机号码
	Exam        int32                 `gorm:"column:exam;type:int(1)" json:"exam"`                                    // 考试（1：没有 0：有）
	Opinion     string                `gorm:"column:opinion;type:varchar(120)" json:"opinion"`                        // 审核意见
	CreateTime  LocalTime             `gorm:"column:create_time;type:datetime;autoCreateTime:true" json:"createTime"` // 创建时间
	UpdateTime  LocalTime             `gorm:"column:update_time;type:datetime;autoUpdateTime:true" json:"updateTime"` // 更新时间
	IsDelete    soft_delete.DeletedAt `gorm:"column:is_delete;type:int(1);softDelete:flag" json:"-"`                  // 逻辑删除
}

// TableName LeaveApply's table name
func (*LeaveApply) TableName() string {
	return TableNameLeaveApply
}
