// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameSysMenu = "sys_menu"

// SysMenu mapped from table <sys_menu>
type SysMenu struct {
	ID         int64     `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	ParentID   int64     `gorm:"column:parent_id;type:bigint(20)" json:"parent_id"`                             // 父菜单ID，一级菜单为0
	Name       string    `gorm:"column:name;type:varchar(64);not null;uniqueIndex:name,priority:1" json:"name"` // 菜单名
	Path       string    `gorm:"column:path;type:varchar(255)" json:"path"`                                     // 菜单URL
	Perms      string    `gorm:"column:perms;type:varchar(255)" json:"perms"`                                   // 授权(多个用逗号分隔，如：user:list,user:create)
	Component  string    `gorm:"column:component;type:varchar(255)" json:"component"`
	Type       int32     `gorm:"column:type;type:int(5);not null" json:"type"`   // 类型     0：目录   1：菜单   2：按钮
	Icon       string    `gorm:"column:icon;type:varchar(32)" json:"icon"`       // 菜单图标
	OrderNum   int32     `gorm:"column:order_num;type:int(11)" json:"order_num"` // 排序
	CreateTime time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
	Status     int32     `gorm:"column:status;type:int(5);not null" json:"status"`
	IsDelete   int32     `gorm:"column:is_delete;type:int(1);not null" json:"is_delete"`
	Version    int32     `gorm:"column:version;type:int(11);not null;default:1" json:"version"`
}

// TableName SysMenu's table name
func (*SysMenu) TableName() string {
	return TableNameSysMenu
}
