// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameSysRoleMenu = "sys_role_menu"

// SysRoleMenu mapped from table <sys_role_menu>
type SysRoleMenu struct {
	ID     int64 `gorm:"column:id;type:bigint(20);primaryKey;autoIncrement:true" json:"id"`
	RoleID int64 `gorm:"column:role_id;type:bigint(20);not null" json:"role_id"`
	MenuID int64 `gorm:"column:menu_id;type:bigint(20);not null" json:"menu_id"`
}

// TableName SysRoleMenu's table name
func (*SysRoleMenu) TableName() string {
	return TableNameSysRoleMenu
}
